platform :ios, '9.0'


target 'DGSwiftExtension_Example' do
    use_frameworks!

  pod 'DGSwiftExtension', :path => '/Users/dhvlsimac/Documents/Projects//iOS/DGSwiftExtension'
  
end

target 'DGSwiftExtension_Tests' do
    use_frameworks!

  pod 'DGSwiftExtension', :path => '/Users/dhvlsimac/Documents/Projects//iOS/DGSwiftExtension'

  
end
